package com.hbl.selfservice.objects;

import java.io.Serializable;

public class EquationLimitFiledsObject  implements Serializable{
	int UD_KFILPK34_KEY	= 0;
	public EquationLimitFiledsObject(int uD_KFILPK34_KEY, int oRC_KEY, String uD_KFILPK34_CREATEBY,
			String uD_KFILPK34_REVOKE, String uD_KFILPK34_PROCESS_INTER_BRAN, String uD_KFILPK34_GROUP,
			int uD_KFILPK34_INTER_BRANCH_DEBIT, String uD_KFILPK34_RESIDENT_BRANCH, int uD_KFILPK34_INTER_BRANCH_CREDI,
			String uD_KFILPK34_BRANCH_NUMBER, int uD_KFILPK34_LOCAL_CREDIT_AMOUN, int uD_KFILPK34_LOCAL_DEBIT_AMOUNT,
			int uD_KFILPK34_DEBIT_AUTHORIZATIO, int uD_KFILPK34_CREDIT_AUTHORIZATI, String uD_EQUATION_KEY) {
		super();
		UD_KFILPK34_KEY = uD_KFILPK34_KEY;
		ORC_KEY = oRC_KEY;
		UD_KFILPK34_CREATEBY = uD_KFILPK34_CREATEBY;
		UD_KFILPK34_REVOKE = uD_KFILPK34_REVOKE;
		UD_KFILPK34_PROCESS_INTER_BRAN = uD_KFILPK34_PROCESS_INTER_BRAN;
		UD_KFILPK34_GROUP = uD_KFILPK34_GROUP;
		UD_KFILPK34_INTER_BRANCH_DEBIT = uD_KFILPK34_INTER_BRANCH_DEBIT;
		UD_KFILPK34_RESIDENT_BRANCH = uD_KFILPK34_RESIDENT_BRANCH;
		UD_KFILPK34_INTER_BRANCH_CREDI = uD_KFILPK34_INTER_BRANCH_CREDI;
		UD_KFILPK34_BRANCH_NUMBER = uD_KFILPK34_BRANCH_NUMBER;
		UD_KFILPK34_LOCAL_CREDIT_AMOUN = uD_KFILPK34_LOCAL_CREDIT_AMOUN;
		UD_KFILPK34_LOCAL_DEBIT_AMOUNT = uD_KFILPK34_LOCAL_DEBIT_AMOUNT;
		UD_KFILPK34_DEBIT_AUTHORIZATIO = uD_KFILPK34_DEBIT_AUTHORIZATIO;
		UD_KFILPK34_CREDIT_AUTHORIZATI = uD_KFILPK34_CREDIT_AUTHORIZATI;
		UD_EQUATION_KEY = uD_EQUATION_KEY;
	}
	int ORC_KEY	= 0;
	public int getUD_KFILPK34_KEY() {
		return UD_KFILPK34_KEY;
	}
	public void setUD_KFILPK34_KEY(int uD_KFILPK34_KEY) {
		UD_KFILPK34_KEY = uD_KFILPK34_KEY;
	}
	public int getORC_KEY() {
		return ORC_KEY;
	}
	public void setORC_KEY(int oRC_KEY) {
		ORC_KEY = oRC_KEY;
	}
	public String getUD_KFILPK34_CREATEBY() {
		return UD_KFILPK34_CREATEBY;
	}
	public void setUD_KFILPK34_CREATEBY(String uD_KFILPK34_CREATEBY) {
		UD_KFILPK34_CREATEBY = uD_KFILPK34_CREATEBY;
	}
	public String getUD_KFILPK34_REVOKE() {
		return UD_KFILPK34_REVOKE;
	}
	public void setUD_KFILPK34_REVOKE(String uD_KFILPK34_REVOKE) {
		UD_KFILPK34_REVOKE = uD_KFILPK34_REVOKE;
	}
	public String getUD_KFILPK34_PROCESS_INTER_BRAN() {
		return UD_KFILPK34_PROCESS_INTER_BRAN;
	}
	public void setUD_KFILPK34_PROCESS_INTER_BRAN(String uD_KFILPK34_PROCESS_INTER_BRAN) {
		UD_KFILPK34_PROCESS_INTER_BRAN = uD_KFILPK34_PROCESS_INTER_BRAN;
	}
	public String getUD_KFILPK34_GROUP() {
		return UD_KFILPK34_GROUP;
	}
	public void setUD_KFILPK34_GROUP(String uD_KFILPK34_GROUP) {
		UD_KFILPK34_GROUP = uD_KFILPK34_GROUP;
	}
	public int getUD_KFILPK34_INTER_BRANCH_DEBIT() {
		return UD_KFILPK34_INTER_BRANCH_DEBIT;
	}
	public void setUD_KFILPK34_INTER_BRANCH_DEBIT(int uD_KFILPK34_INTER_BRANCH_DEBIT) {
		UD_KFILPK34_INTER_BRANCH_DEBIT = uD_KFILPK34_INTER_BRANCH_DEBIT;
	}
	public String getUD_KFILPK34_RESIDENT_BRANCH() {
		return UD_KFILPK34_RESIDENT_BRANCH;
	}
	public void setUD_KFILPK34_RESIDENT_BRANCH(String uD_KFILPK34_RESIDENT_BRANCH) {
		UD_KFILPK34_RESIDENT_BRANCH = uD_KFILPK34_RESIDENT_BRANCH;
	}
	public int getUD_KFILPK34_INTER_BRANCH_CREDI() {
		return UD_KFILPK34_INTER_BRANCH_CREDI;
	}
	public void setUD_KFILPK34_INTER_BRANCH_CREDI(int uD_KFILPK34_INTER_BRANCH_CREDI) {
		UD_KFILPK34_INTER_BRANCH_CREDI = uD_KFILPK34_INTER_BRANCH_CREDI;
	}
	public String getUD_KFILPK34_BRANCH_NUMBER() {
		return UD_KFILPK34_BRANCH_NUMBER;
	}
	public void setUD_KFILPK34_BRANCH_NUMBER(String uD_KFILPK34_BRANCH_NUMBER) {
		UD_KFILPK34_BRANCH_NUMBER = uD_KFILPK34_BRANCH_NUMBER;
	}
	public int getUD_KFILPK34_LOCAL_CREDIT_AMOUN() {
		return UD_KFILPK34_LOCAL_CREDIT_AMOUN;
	}
	public void setUD_KFILPK34_LOCAL_CREDIT_AMOUN(int uD_KFILPK34_LOCAL_CREDIT_AMOUN) {
		UD_KFILPK34_LOCAL_CREDIT_AMOUN = uD_KFILPK34_LOCAL_CREDIT_AMOUN;
	}
	public int getUD_KFILPK34_LOCAL_DEBIT_AMOUNT() {
		return UD_KFILPK34_LOCAL_DEBIT_AMOUNT;
	}
	public void setUD_KFILPK34_LOCAL_DEBIT_AMOUNT(int uD_KFILPK34_LOCAL_DEBIT_AMOUNT) {
		UD_KFILPK34_LOCAL_DEBIT_AMOUNT = uD_KFILPK34_LOCAL_DEBIT_AMOUNT;
	}
	public int getUD_KFILPK34_DEBIT_AUTHORIZATIO() {
		return UD_KFILPK34_DEBIT_AUTHORIZATIO;
	}
	public void setUD_KFILPK34_DEBIT_AUTHORIZATIO(int uD_KFILPK34_DEBIT_AUTHORIZATIO) {
		UD_KFILPK34_DEBIT_AUTHORIZATIO = uD_KFILPK34_DEBIT_AUTHORIZATIO;
	}
	public int getUD_KFILPK34_CREDIT_AUTHORIZATI() {
		return UD_KFILPK34_CREDIT_AUTHORIZATI;
	}
	public void setUD_KFILPK34_CREDIT_AUTHORIZATI(int uD_KFILPK34_CREDIT_AUTHORIZATI) {
		UD_KFILPK34_CREDIT_AUTHORIZATI = uD_KFILPK34_CREDIT_AUTHORIZATI;
	}
	public String getUD_EQUATION_KEY() {
		return UD_EQUATION_KEY;
	}
	public void setUD_EQUATION_KEY(String uD_EQUATION_KEY) {
		UD_EQUATION_KEY = uD_EQUATION_KEY;
	}
	String UD_KFILPK34_CREATEBY	= null;
	String UD_KFILPK34_REVOKE	= null;
	String UD_KFILPK34_PROCESS_INTER_BRAN	= null;
	String UD_KFILPK34_GROUP	= null;
	int UD_KFILPK34_INTER_BRANCH_DEBIT	= 0;
	String UD_KFILPK34_RESIDENT_BRANCH	= null;
	int UD_KFILPK34_INTER_BRANCH_CREDI	= 0;
	String UD_KFILPK34_BRANCH_NUMBER	= null;
	int UD_KFILPK34_LOCAL_CREDIT_AMOUN	= 0;
	int UD_KFILPK34_LOCAL_DEBIT_AMOUNT	= 0;
	int UD_KFILPK34_DEBIT_AUTHORIZATIO	= 0;
	int UD_KFILPK34_CREDIT_AUTHORIZATI	= 0;
	String UD_EQUATION_KEY	= null;
}
