package com.hbl.approvalrequests;

public  class PredefinedConst {
	public static String PENDING_APPROVALS_QUERY = "select ASSIGNEES, ASSIGNEEGROUPSDISPLAYNAME, ASSIGNEEGROUPS, ASSIGNEEUSERS ,CREATOR,APPROVERS , TEXTATTRIBUTE2 as REQUEST_TYPE,"
			+ "TEXTATTRIBUTE6 as ITEM_NAME,TITLE,IDENTIFICATIONKEY , TASKID, TEXTATTRIBUTE1 as REQ_ID,STATE "
			+ " from WFTASK where ASSIGNEES like ? and STATE=? and  TEXTATTRIBUTE6 is not null";
	
	public static String PENDING_APPROVAL_DETAILS_QUERY ="select ASSIGNEES, ASSIGNEEGROUPSDISPLAYNAME, ASSIGNEEGROUPS, ASSIGNEEUSERS ,STATE,CREATOR,APPROVERS ,OUTCOME, TEXTATTRIBUTE2 as REQUEST_TYPE," + 
			"TEXTATTRIBUTE6 as ITEM_NAME,TITLE,IDENTIFICATIONKEY, STAGE , TASKID, TEXTATTRIBUTE1 as REQ_ID " + 
			"from WFTASKHISTORY where IDENTIFICATIONKEY =? and STATE =?";
	
	public static String TRACK_REQUEST_QUERY = "select APPROVERS,OUTCOME,ASSIGNEES, ASSIGNEEGROUPSDISPLAYNAME,CREATEDDATE, ASSIGNEEGROUPS, ASSIGNEEUSERS ,CREATOR,APPROVERS , TEXTATTRIBUTE2 as REQUEST_TYPE,"
			+ "TEXTATTRIBUTE6 as ITEM_NAME,TITLE,IDENTIFICATIONKEY , TASKID, TEXTATTRIBUTE1 as REQ_ID,STATE "
			+ " from WFTASK where IDENTIFICATIONKEY=?";
	public static String TASK_ID_QUERY ="SELECT TASKID FROM WFTASK WHERE IDENTIFICATIONKEY =?" ;
	
	public static String EQUATION_LIMIT_REQUEST_QUERY ="select REQUEST_ID,REQUEST_TYPE,REQUEST_STATUS,APPROVER_LEVEL,GROUP_NAME,STATUS,STATE,USER_KEY,ORC_KEY ,CREATE_DATE ,UPDATE_DATE ,COMPLETED_DATE  from EQU_REQUEST where USER_KEY=?";
	public static String EQUATION_LIMITS_OIM_SCHEMA = "select UD_KFILPK34_KEY,ORC_KEY,POL_KEY,UD_KFILPK34_UPDATEBY,UD_KFILPK34_UPDATE,UD_KFILPK34_CREATEBY,UD_KFILPK34_CREATE,UD_KFILPK34_NOTE,UD_KFILPK34_ROWVER,UD_KFILPK34_DATA_LEVEL,UD_KFILPK34_VERSION,REQUEST_KEY ,UD_KFILPK34_REVOKE,UD_KFILPK34_PROCESS_INTER_BRAN,UD_KFILPK34_GROUP,UD_KFILPK34_INTER_BRANCH_DEBIT,UD_KFILPK34_RESIDENT_BRANCH,UD_KFILPK34_INTER_BRANCH_CREDI,UD_KFILPK34_BRANCH_NO,UD_KFILPK34_LOCAL_CREDIT_AMOUN,UD_KFILPK34_LOCAL_DEBIT_AMOUNT,UD_KFILPK34_DEBIT_AUTHORIZATIO,UD_KFILPK34_CREDIT_AUTHORIZATI,UD_EQUATION_KEY  from UD_KFILPK34 where orc_key=? order by UD_KFILPK34_RESIDENT_BRANCH asc ";
	//private static String INITIATE_EQUATION_MODIFY_LIMIT = "Insert into EQU_REQUEST (REQUEST_TYPE,REQUEST_STATUS,APPROVER_LEVEL,GROUP_NAME,STATUS,STATE,USER_KEY,ORC_KEY,REQUESTER) values ('Modify','In-Progress','1','1234','Pending','1','123','1123',1123);";
	public static String INITIATE_EQUATION_MODIFY_LIMIT = "Insert into EQU_REQUEST (REQUEST_TYPE,REQUEST_STATUS,APPROVER_LEVEL,GROUP_NAME,STATUS,STATE,USER_KEY,ORC_KEY,CREATE_DATE,REQUESTER,FIRST_LEV_APPRVER,SEC_LEV_APPRVER,THIRD_LEV_APPRVER,CURRENT_APPROVER) values (?,?,?,?,?,?,?,?,?,?,?,?,?,?)";
	
	public static String EQUATION_APPROVAL_HISTORY_UPDATE = "Insert into EQU_REQ_APPRV_HIST (REQUEST_ID,APPROVER_KEY,ACTION,APPROVAL_COMMENTS,STAGE) values (?,?,?,?,?)";
	
	public static String EQUATION_REQ_LIMIT_DATA_INSERT ="Insert into EQU_REQUEST_DATA (REQUEST_ID,GROUP_NAME,ACTION,"
			+ "UD_KFILPK34_PROCESS_INTER_BRAN,UD_KFILPK34_GROUP,"
			+ "UD_KFILPK34_INTER_BRANCH_DEBIT,UD_KFILPK34_RESIDENT_BRANCH,UD_KFILPK34_INTER_BRANCH_CREDI,"
			+ "UD_KFILPK34_BRANCH_NUMBER,UD_KFILPK34_LOCAL_CREDIT_AMOUN,UD_KFILPK34_LOCAL_DEBIT_AMOUNT,"
			+ "UD_KFILPK34_DEBIT_AUTHORIZATIO,UD_KFILPK34_CREDIT_AUTHORIZATI,ROW_NUMBER_TO_UPATE) "
			+ "values (?,?,?,?,?,?,?,?,?,?,?,?,?,?)";
	public static String GET_EQUATION_REQ_LIMIT_DATA ="select REQUEST_ID,GROUP_NAME,ACTION,"
			+ "UD_KFILPK34_PROCESS_INTER_BRAN,UD_KFILPK34_GROUP,"
			+ "UD_KFILPK34_INTER_BRANCH_DEBIT,UD_KFILPK34_RESIDENT_BRANCH,UD_KFILPK34_INTER_BRANCH_CREDI,"
			+ "UD_KFILPK34_BRANCH_NUMBER,UD_KFILPK34_LOCAL_CREDIT_AMOUN,UD_KFILPK34_LOCAL_DEBIT_AMOUNT,"
			+ "UD_KFILPK34_DEBIT_AUTHORIZATIO,UD_KFILPK34_CREDIT_AUTHORIZATI,ROW_NUMBER_TO_UPATE from EQU_REQUEST_DATA where REQUEST_ID= ? ";
			 
	
	public static String LIMITS_GET_PENDING_APPROVALS = "select REQUEST_ID,REQUEST_TYPE, REQUEST_STATUS, APPROVER_LEVEL, GROUP_NAME, STATE, STATUS, " + 
			"USER_KEY, ORC_KEY, CREATE_DATE, UPDATE_DATE, REQUESTER, FIRST_LEV_APPRVER,  " + 
			"SEC_LEV_APPRVER, THIRD_LEV_APPRVER, CURRENT_APPROVER " + 
			"from EQU_REQUEST where CURRENT_APPROVER =?" + 
			"AND REQUEST_STATUS =?";
	public static String LIMITS_GET_PENDING_APPROVALS_WITH_LAM = "select REQUEST_ID,REQUEST_TYPE, REQUEST_STATUS, APPROVER_LEVEL, GROUP_NAME, STATE, STATUS, " + 
			"USER_KEY, ORC_KEY, CREATE_DATE, UPDATE_DATE, REQUESTER, FIRST_LEV_APPRVER,  " + 
			"SEC_LEV_APPRVER, THIRD_LEV_APPRVER, CURRENT_APPROVER " + 
			"from EQU_REQUEST where CURRENT_APPROVER =? OR CURRENT_APPROVER =?" + 
			"AND REQUEST_STATUS =?";
	public static String LIMITS_GET_REQUEST_DETAILS = "select REQUEST_ID,REQUEST_TYPE, REQUEST_STATUS, APPROVER_LEVEL, GROUP_NAME, STATE, STATUS, " + 
			"USER_KEY, ORC_KEY, CREATE_DATE, UPDATE_DATE, REQUESTER, FIRST_LEV_APPRVER,  " + 
			"SEC_LEV_APPRVER, THIRD_LEV_APPRVER, CURRENT_APPROVER " + 
			"from EQU_REQUEST where REQUEST_ID =?";
	public static String LIMITS_APPROVAL_HISTORY ="SELECT EQHST.APPRV_HIST_ID as H_APPRV_HIST_ID ,EQHST.REQUEST_ID as H_REQUEST_ID ,EQHST.APPROVER_KEY H_APPROVER_KEY,  " + 
			"EQHST.APPROVAL_COMMENTS as H_APPROVAL_COMMENTS, EQHST.STAGE as H_STAGE, EQHST.ACTION as H_ACTION, " + 
			"EQRQST.REQUEST_TYPE as R_REQUEST_TYPE, EQRQST.STATE as R_STATE, EQRQST.CREATE_DATE as R_CREATE_DATE, EQRQST.REQUESTER as R_REQUESTER, EQRQST.STATUS as R_STATUS  " + 
			"FROM EQU_REQ_APPRV_HIST EQHST  " + 
			"INNER JOIN EQU_REQUEST EQRQST " + 
			"ON EQHST.REQUEST_ID = EQRQST.REQUEST_ID " + 
			"WHERE EQRQST.REQUEST_ID = ?  AND EQRQST.STATUS ='Awaiting Approval' " + 
			"ORDER BY APPRV_HIST_ID";
	
	public static String Get_AS400_CSG = "select * from USR inner join OIU on USR.USR_KEY=OIU.USR_KEY inner join UD_AS400CSG on OIU.ORC_KEY=UD_AS400CSG.ORC_KEY \r\n" + 
			"where OIU.APP_INSTANCE_KEY =? and USR.USR_LOGIN=?";
	public static String Get_AS400_CSP = "select * from USR inner join OIU on USR.USR_KEY=OIU.USR_KEY inner join UD_AS400CSP on OIU.ORC_KEY=UD_AS400CSP.ORC_KEY \r\n" + 
			"where OIU.APP_INSTANCE_KEY =? and USR.USR_LOGIN=?";
	
	public static String Get_EQUATION_26 = "select * from USR inner join OIU on USR.USR_KEY=OIU.USR_KEY inner join UD_KFILPK26 on OIU.ORC_KEY=UD_KFILPK26.ORC_KEY \r\n" + 
			"where OIU.APP_INSTANCE_KEY =? and USR.USR_LOGIN=?";
	
	public static String Get_EQUATION_7 = "select * from USR inner join OIU on USR.USR_KEY=OIU.USR_KEY inner join UD_KAPBASE7 on OIU.ORC_KEY=UD_KAPBASE7.ORC_KEY \r\n" + 
			"where OIU.APP_INSTANCE_KEY =? and USR.USR_LOGIN=?";

	public static String Get_EQUATION_34 = "select * from USR inner join OIU on USR.USR_KEY=OIU.USR_KEY inner join UD_KFILPK34 on OIU.ORC_KEY=UD_KFILPK34.ORC_KEY \r\n" + 
			"where OIU.APP_INSTANCE_KEY =? and USR.USR_LOGIN=?";

	public static String Get_EQUATION_27 = "select * from USR inner join OIU on USR.USR_KEY=OIU.USR_KEY inner join UD_KFILPK27 on OIU.ORC_KEY=UD_KFILPK27.ORC_KEY \r\n" + 
			"where OIU.APP_INSTANCE_KEY =? and USR.USR_LOGIN=?";


	public static String Get_Equation_Group = "select * from USR inner join OIU on USR.USR_KEY=OIU.USR_KEY inner join UD_KFILPK25 on OIU.ORC_KEY=UD_KFILPK25.ORC_KEY \r\n" + 
			"where OIU.APP_INSTANCE_KEY =? and USR.USR_LOGIN=?";
	
	public static String Get_Request_Comments = "select c.WFCOMMENT,c.COMMENTDATE from WFTASK t INNER join WFCOMMENTS c on t.TASKID=c.TASKID where t.IDENTIFICATIONKEY=?";
	
	 
	
}
